import { createSlice } from '@reduxjs/toolkit';

// Define the initial state for appointments
const initialState = {
  appointments: [],
};

// Create the appointments slice
const appointmentsSlice = createSlice({
  name: 'appointments',
  initialState,
  reducers: {
    // Add an action to add a new appointment
    addAppointment: (state, action) => {
      state.appointments.push(action.payload);
    },
    // Add an action to remove an appointment by ID
    removeAppointment: (state, action) => {
      state.appointments = state.appointments.filter(
        (appointment) => appointment.id !== action.payload
      );
    },
    // Add other actions as needed for your application
  },
});

// Export the actions generated by createSlice
export const { addAppointment, removeAppointment } = appointmentsSlice.actions;

// Export the reducer
export default appointmentsSlice.reducer;
