import { createSlice } from '@reduxjs/toolkit';

// Define the initial state for notifications
const initialState = {
  notifications: [],
};

// Create the notifications slice
const notificationsSlice = createSlice({
  name: 'notifications',
  initialState,
  reducers: {
    // Add an action to add a new notification
    addNotification: (state, action) => {
      state.notifications.push(action.payload);
    },
    // Add an action to remove a notification by ID
    removeNotification: (state, action) => {
      state.notifications = state.notifications.filter(
        (notification) => notification.id !== action.payload
      );
    },
    // Add other actions as needed for your application
  },
});

// Export the actions generated by createSlice
export const { addNotification, removeNotification } = notificationsSlice.actions;

// Export the reducer
export default notificationsSlice.reducer;
